Develop/czaplejewiczp/test fake store
TTMS-TRAINING/FakeStorePlaywright pull request #20
Opened 2024-09-24 17:37 UTC by pawelcz44

Main jest pusty, nie wiem jak to potem zmergujemy, zmienione są tak naprawdę tylko 3 pliki. WishlistPage.ts, wishlist.spec.ts i dodana jedna nowa wartość w AcountTestData.ts

2024-09-25 08:27 UTC, Saganeiro requested changes

2024-09-25 08:27 UTC, Saganeiro commented on tests/wishlist.spec.ts
Formatuj pliki

2024-09-25 08:27 UTC, Saganeiro commented on tests/test-1.spec.ts
Usun ten pusty test

2024-09-25 08:48 UTC, Saganeiro commented on tests/pages/WishlistPage.ts
> +        }
Brakuje asercji sprawdzającej czy akcja usuwania elementów zakonczyłą sie sukcesem

2024-09-25 08:52 UTC, Saganeiro commented on tests/pages/WishlistPage.ts
>          console.log('Kliknięcie na element wishlistName');
Czy potrzebujemy consol logów? Raczej uzywamy ich do debuggowania testu i nie wrzucamy kiedy test jest gotowy

2024-09-25 08:55 UTC, pawelcz44 commented on tests/pages/WishlistPage.ts
> +        }
Asercja jest dodana z poziomu tworzenia testu:
    await expect(page.locator('td')).toContainText('No products added to the wishlist'); w przypadku gdy usuwany całą listę  i lista jest pusta albo przy usuwaniu pojedyńćzego:
        // Pobierz liczbę produktów przed usunięciem
        const productCountBefore = await wishlistPage.getProductCount();
        console.log(`Liczba produktów przed usunięciem: ${productCountBefore}`);

        // Usuń pierwszy produkt
        await wishlistPage.removeProduct(0);
        await page.waitForTimeout(1000); // Czekaj przez 1000 ms (1 sekunda)

        // Pobierz liczbę produktów po usunięciu
        const productCountAfter = await wishlistPage.getProductCount();
        console.log(`Liczba produktów po usunięciu: ${productCountAfter}`);

        await expect(productCountAfter).toBe(productCountBefore - 1); // Oczekujemy, że lista produktów zmniejszy się o 1

można to przenieść do samej metody, zostało to zaimplementowane w ten sposób żeby podstawowa funkcja była bardziej uniwersalna

2024-09-25 08:57 UTC, pawelcz44 commented on tests/pages/WishlistPage.ts
>          console.log('Kliknięcie na element wishlistName');
Tak, na tym etapie console logi są mi potrzebne, zakładam że przy rozbudowaniu testów w dalszej fazie trzeba będzie dodać kilka sprawdzań (np dodanie do koszyka z poprawnym sprawdzeniem wartości z poziomu wishlist), ja bym jeszcze zostawił te console logi, zwłaszcza że trochę uczę się ich używać jeszcze :P

2024-09-25 09:01 UTC, pawelcz44 commented on tests/wishlist.spec.ts
zrobione

2024-09-25 09:18 UTC, Saganeiro approved these changes, later dismissed

2024-09-26 14:53 UTC, Saganeiro requested changes

2024-09-26 14:53 UTC, Saganeiro commented on tests/basektTests.spec.t
1. Formatuj pliki
2. Staraj się usuwać zakomentowane linijki

2024-09-26 14:53 UTC, Saganeiro commented on tests/storePage.spec.ts
Format

2024-09-27 08:34 UTC, pawelcz44 commented on tests/basektTests.spec.t
usunięty jakiś kod który wywalał wszystkie testy na github

2024-09-27 08:34 UTC, pawelcz44 commented on tests/storePage.spec.ts
done

2024-09-27 11:12 UTC, kamilakrystyna commented on tests/basektTests.spec.t
> +import { test, expect } from '@playwright/test';
Jest sens trzymać ten test i wrzucać go na maina skoro nie działa jak należy, nikt nie wie czyj on i w ogóle ? ;)

2024-09-27 12:55 UTC, pawelcz44 commented on tests/basektTests.spec.t
> +import { test, expect } from '@playwright/test';
usunięty :)

2024-09-29 18:31 UTC, closed without merging