Develop/jurczuka/manually inserting number of items
TTMS-TRAINING/FakeStorePlaywright pull request #21
Opened 2024-09-25 07:44 UTC by AJquality

2024-09-25 08:31 UTC, Saganeiro requested changes

2024-09-25 08:31 UTC, Saganeiro commented on e2e/example.spec.ts
Usun ten plik example

2024-09-25 08:31 UTC, Saganeiro commented on tests-examples/demo-todo-app.spec.ts
Usun ten plik example

2024-09-25 08:31 UTC, Saganeiro commented on tests/pages/StorePage.ts
BRak formatowania

2024-09-25 10:22 UTC, AJquality commented on tests/pages/StorePage.ts
Już sformatowane i usunięte pliki z przykładowymi testami

2024-09-26 14:46 UTC, Saganeiro submitted a review, later dismissed

2024-09-26 19:01 UTC, Saganeiro commented
Konflikt masz rozwiąz plx

2024-09-27 12:20 UTC, pawelcz44 approved these changes

2024-09-27 12:21 UTC, Saganeiro approved these changes

2024-09-27 12:21 UTC, merged