Task Privacy policy check
TTMS-TRAINING/FakeStorePlaywright pull request #39
Opened 2024-10-08 09:54 UTC by ErnestJurek

2024-10-08 11:28 UTC, pawelcz44 submitted a review, later dismissed

2024-10-09 08:36 UTC, kamilakrystyna requested changes

2024-10-09 08:36 UTC, kamilakrystyna commented on tests/privacyPolicy.spec.ts
> +        await accountPage.register(AccountTestData.CorrectEmailLogin);
Zwróć uwagę, że używasz tu metody Register a pobierasz dane CorrectEmailLogin gdzie są podane do logowania. Wynikiem tego jest że Twoje pola do register nie są wypełniane i użytkownik nie zarejestrował się . 
Test przechodzi bo aby przejść do polityki prywatności nie trzeba być zarejestrowanym.
Albo wyrzuć rejestracje albo użyj danych do rejestracji.

2024-10-10 16:26 UTC, kamilakrystyna approved these changes

2024-10-11 10:06 UTC, Saganeiro approved these changes

2024-10-11 10:07 UTC, merged